spring.datasource.url=jdbc:postgresql://localhost:5433/eshop
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE